### ISSUE TITLE
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

### ISSUE THREAD

**Issue by captainleviftw** [nathfreder/pocketmine-installer#4]
PocketMine.exe -> Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: | PocketMine-MP.exe
-- | --
Publisher: | Unknown publisher

**Comment by nathfreder** [comment]
Can you send a screenshot?

**Comment by nathfreder** [comment]
Thanks for the report, I’ve found the issue!
